[browser]
gatherUsageStats = false

[server]
headless = true

[theme]
primaryColor = "#1F3864"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#1F2937"
font = "sans serif"
base = "light"
